from __future__ import annotations

from datetime import datetime, timedelta, timezone

from monitoring_agent.client import CURRENT_ENDPOINT_KEYS
from monitoring_agent.incident_store import IncidentStateStore
from monitoring_agent.incidents import (
    CycleSnapshot,
    EndpointObservationFact,
    IncidentEvaluation,
    evaluate_incident_lifecycle,
)
from monitoring_agent.reporting import (
    DRAFT_PROMPT_LINE,
    build_monitoring_report_snapshot,
    redact_monitoring_text,
    render_monitoring_report,
    render_programming_agent_prompt,
)


BASE_TIME = datetime(2026, 8, 14, 8, 0, tzinfo=timezone.utc)


def _cycle(
    sequence: int,
    *,
    payload_status: dict[str, str] | None = None,
    transport: dict[str, str] | None = None,
    historical: bool = False,
) -> CycleSnapshot:
    payload_status = payload_status or {}
    transport = transport or {}
    return CycleSnapshot(
        cycle_sequence=sequence,
        observed_at=BASE_TIME + timedelta(seconds=60 * sequence),
        historical=historical,
        endpoint_observations=tuple(
            EndpointObservationFact(
                endpoint_key=endpoint_key,
                transport_status=transport.get(endpoint_key, "success"),
                http_status=(
                    200
                    if transport.get(endpoint_key, "success") == "success"
                    else None
                ),
                payload_status=payload_status.get(endpoint_key, "ok"),
            )
            for endpoint_key in CURRENT_ENDPOINT_KEYS
        ),
    )


def _empty_evaluation() -> IncidentEvaluation:
    return IncidentEvaluation(rule_version=1, transitions=(), states=())


def test_render_healthy_report_has_stable_snapshot():
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=_empty_evaluation(),
        latest_heartbeat_status="healthy",
        observation_count=9,
        transport_failure_count=0,
    )

    assert render_monitoring_report(snapshot) == (
        "# Monitoring agent report\n"
        "\n"
        "Generated at: 2026-08-14T08:00:00+00:00\n"
        "Renderer version: 1\n"
        "Summary status: healthy\n"
        "\n"
        "## Verified facts\n"
        "- [info] generated_at: 2026-08-14T08:00:00+00:00\n"
        "- [info] incident_rule_version: 1\n"
        "- [info] incident_states: total=0, active=0, candidate=0, resolved=0\n"
        "- [info] transition_count: 0\n"
        "- [info] latest_heartbeat_status: healthy\n"
        "- [info] latest_observation_count: 9\n"
        "- [info] latest_transport_failure_count: 0\n"
        "\n"
        "## Rule conclusions\n"
        "- [info] no incident transition: No active incident, candidate, or "
        "recovery transition in the supplied evaluation.\n"
        "\n"
        "## Historical qualifications\n"
        "- [info] none: No historical qualifiers or evidence gaps supplied.\n"
        "\n"
        "## Hypotheses / not yet verified\n"
        "- [info] none: No hypotheses generated by this deterministic renderer.\n"
        "\n"
        "## Outbox / delivery state\n"
        "- [info] delivery_enabled: false\n"
        "- [info] outbox_snapshot: not supplied; no delivery attempted\n"
        "\n"
        "## Safety boundary\n"
        "- [critical] no delivery side effects: Delivery disabled by design. "
        "Rendering this report does not send email, open network connections, "
        "mutate state, or authorize a delivery worker.\n"
        "- [critical] sanitized inputs only: Report inputs must be normalized "
        "facts; do not pass credentials, raw payloads, cookies, tokens, or "
        "private file contents.\n"
    )


def test_render_degraded_report_keeps_candidate_separate_from_incident():
    evaluation = evaluate_incident_lifecycle(
        [_cycle(1, payload_status={"system_database": "degraded"})]
    )
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=evaluation,
        latest_heartbeat_status="degraded",
        observation_count=9,
        transport_failure_count=0,
    )

    report = render_monitoring_report(snapshot)

    assert "Summary status: degraded" in report
    assert (
        "- [warning] candidate endpoint:system_database: severity=warning, "
        "reason=endpoint_payload_status:degraded"
    ) in report
    assert "- [warning] suppressed endpoint:system_database: status=candidate" in report
    assert "delivery_enabled: false" in report


def test_render_incident_report_includes_outbox_intent_without_delivery(tmp_path):
    evaluation = evaluate_incident_lifecycle(
        [
            _cycle(1, payload_status={"system_database": "degraded"}),
            _cycle(2, payload_status={"system_database": "degraded"}),
        ]
    )
    store_snapshot = IncidentStateStore(tmp_path).apply_evaluation(
        evaluation,
        now=BASE_TIME,
    )
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=evaluation,
        store_snapshot=store_snapshot,
        latest_heartbeat_status="degraded",
        observation_count=9,
        transport_failure_count=0,
    )

    report = render_monitoring_report(snapshot)

    assert "Summary status: incident" in report
    assert "- [warning] active endpoint:system_database:" in report
    assert "- [warning] opened endpoint:system_database: status=active" in report
    assert (
        "- [info] outbox_counts: pending=1, in_progress=0, sent=0, "
        "dead_letter=0"
    ) in report
    assert "- [info] pending opened endpoint:system_database:" in report
    assert "idempotency_key" not in report
    assert "Delivery disabled by design" in report


def test_render_recovery_report_has_recovery_example():
    evaluation = evaluate_incident_lifecycle(
        [
            _cycle(1, payload_status={"system_database": "degraded"}),
            _cycle(2, payload_status={"system_database": "degraded"}),
            _cycle(3),
            _cycle(4),
        ]
    )
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=evaluation,
        latest_heartbeat_status="healthy",
        observation_count=9,
        transport_failure_count=0,
    )

    report = render_monitoring_report(snapshot)

    assert "Summary status: recovered" in report
    assert "- [warning] resolved endpoint:system_database:" in report
    assert (
        "- [warning] recovered endpoint:system_database: status=resolved, "
        "reason=recovery_confirmed"
    ) in report


def test_historical_evidence_and_hypotheses_are_visibly_separate():
    evaluation = evaluate_incident_lifecycle(
        [_cycle(1, transport={"system_runtime": "schema_error"}, historical=True)]
    )
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=evaluation,
        evidence_gaps=("heartbeat_transition_history_not_persisted",),
        historical_notes=("0.7 to 0.8.1 migration created planned stop evidence",),
        hypotheses=("target process restart timing requires later operator review",),
    )

    report = render_monitoring_report(snapshot)

    assert "## Rule conclusions" in report
    assert (
        "## Historical qualifications\n"
        "- [info] historical note: 0.7 to 0.8.1 migration created planned stop "
        "evidence"
    ) in report
    assert (
        "- [warning] historical-only observer_self_health:facade_contract: "
        "action=suppressed"
    ) in report
    assert (
        "## Hypotheses / not yet verified\n"
        "- [info] hypothesis: target process restart timing requires later "
        "operator review"
    ) in report


def test_programming_agent_prompt_is_draft_only_bounded_and_non_authorizing():
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=_empty_evaluation(),
        latest_heartbeat_status="healthy",
        observation_count=9,
        transport_failure_count=0,
    )

    prompt = render_programming_agent_prompt(snapshot, max_chars=4_000)

    assert prompt.startswith(DRAFT_PROMPT_LINE)
    assert "Propose diagnostics and success criteria; do not perform them." in prompt
    assert (
        "No command execution, network contact, state mutation, service restart, "
        "delivery attempt, or alert replacement is authorized."
    ) in prompt
    assert "summary_status: healthy" in prompt
    assert "delivery_enabled=false" in prompt
    assert len(prompt) <= 4_000


def test_report_and_prompt_redact_secrets_paths_queries_and_private_ids():
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=_empty_evaluation(),
        historical_notes=(
            "token=super-secret-token",
            "Authorization: Bearer abcdefgh123456789",
            "https://platform.example/health?token=super-secret-token#fragment",
            r"C:\Users\tra\PycharmProjects\monitoring-agent-0.8.1\.env",
            "private-run-12345",
        ),
    )

    rendered = "\n".join(
        [
            render_monitoring_report(snapshot),
            render_programming_agent_prompt(snapshot),
            redact_monitoring_text("api_key: abcdefgh123456789"),
        ]
    )

    assert "super-secret-token" not in rendered
    assert "abcdefgh123456789" not in rendered
    assert r"C:\Users\tra" not in rendered
    assert "private-run-12345" not in rendered
    assert "[redacted]" in rendered
    assert "[redacted-query]" in rendered
    assert "[redacted-windows-user-path]" in rendered
    assert "[redacted-private-id]" in rendered


def test_prompt_truncates_with_explicit_marker():
    snapshot = build_monitoring_report_snapshot(
        generated_at=BASE_TIME,
        incident_evaluation=_empty_evaluation(),
        hypotheses=tuple(f"hypothesis {index}" for index in range(50)),
    )

    prompt = render_programming_agent_prompt(snapshot, max_chars=180)

    assert prompt.startswith("DRAFT ONLY")
    assert len(prompt) <= 180
    assert "truncated: monitoring report exceeded configured character limit" in prompt
