"""Independent read-only monitoring observer."""

from .audit import StateAuditError, build_state_audit
from .client import APPROVED_ENDPOINTS, HealthClient
from .delivery import (
    DeliveryAttemptResult,
    DeliveryEnvelope,
    OutlookEmailTransport,
    TestDeliveryPolicy,
    build_test_delivery_envelope,
    deliver_due_test_delivery_intents,
    hash_delivery_recipient,
    normalize_delivery_recipient,
    send_email_outlook,
    validate_outlook_email_environment,
    validate_test_delivery_policy,
)
from .incidents import (
    DEFAULT_INCIDENT_RULES,
    CycleSnapshot,
    EndpointObservationFact,
    IncidentEvaluation,
    IncidentRules,
    evaluate_incident_lifecycle,
)
from .incident_store import (
    IncidentStateStore,
    IncidentStoreError,
    IncidentStoreLimits,
)
from .interpretation import (
    InterpretationPolicy,
    InterpretationProviderOutput,
    InterpretationRequest,
    InterpretationResult,
    build_interpretation_prompt,
    interpret_confirmed_incidents,
)
from .observer import run_observation_cycle
from .orchestrator import (
    AgentRegistryEntry,
    AgentSnapshot,
    CorrelationFinding,
    OrchestratorError,
    OrchestratorSnapshot,
    build_orchestrator_snapshot,
    correlate_agent_snapshots,
    load_registry_file,
    registry_entries_from_payload,
    render_orchestrator_snapshot,
)
from .reporting import (
    MonitoringReportSnapshot,
    ReportFact,
    build_monitoring_report_snapshot,
    redact_monitoring_text,
    render_monitoring_report,
    render_programming_agent_prompt,
)
from .runtime_shadow import (
    ShadowRuntimeSummary,
    apply_shadow_incident_cycle,
    build_incident_store,
    build_incident_store_limits,
    summarize_shadow_incident_snapshot,
)
from .settings import RuntimeSettings
from .shadow_pilot import (
    ShadowPilotBlindSpot,
    ShadowPilotComparison,
    ShadowPilotEvent,
    blind_spots_from_shadow_pilot_payload,
    build_shadow_pilot_comparison,
    events_from_incident_evaluation,
    events_from_incident_transition_records,
    events_from_shadow_pilot_payload,
    render_shadow_pilot_comparison,
    shadow_pilot_events_payload,
)
from .store import ObserverStore, StateRetentionError

__all__ = [
    "APPROVED_ENDPOINTS",
    "DEFAULT_INCIDENT_RULES",
    "CycleSnapshot",
    "DeliveryAttemptResult",
    "DeliveryEnvelope",
    "EndpointObservationFact",
    "HealthClient",
    "IncidentEvaluation",
    "IncidentStateStore",
    "IncidentStoreError",
    "IncidentStoreLimits",
    "InterpretationPolicy",
    "InterpretationProviderOutput",
    "InterpretationRequest",
    "InterpretationResult",
    "IncidentRules",
    "MonitoringReportSnapshot",
    "AgentRegistryEntry",
    "AgentSnapshot",
    "ObserverStore",
    "CorrelationFinding",
    "OrchestratorError",
    "OrchestratorSnapshot",
    "OutlookEmailTransport",
    "ReportFact",
    "RuntimeSettings",
    "StateRetentionError",
    "StateAuditError",
    "ShadowRuntimeSummary",
    "ShadowPilotBlindSpot",
    "ShadowPilotComparison",
    "ShadowPilotEvent",
    "apply_shadow_incident_cycle",
    "build_incident_store",
    "build_incident_store_limits",
    "TestDeliveryPolicy",
    "build_test_delivery_envelope",
    "deliver_due_test_delivery_intents",
    "build_state_audit",
    "build_monitoring_report_snapshot",
    "build_orchestrator_snapshot",
    "build_shadow_pilot_comparison",
    "build_interpretation_prompt",
    "blind_spots_from_shadow_pilot_payload",
    "correlate_agent_snapshots",
    "events_from_incident_evaluation",
    "events_from_incident_transition_records",
    "events_from_shadow_pilot_payload",
    "evaluate_incident_lifecycle",
    "hash_delivery_recipient",
    "load_registry_file",
    "normalize_delivery_recipient",
    "redact_monitoring_text",
    "registry_entries_from_payload",
    "render_monitoring_report",
    "render_orchestrator_snapshot",
    "render_programming_agent_prompt",
    "render_shadow_pilot_comparison",
    "shadow_pilot_events_payload",
    "interpret_confirmed_incidents",
    "send_email_outlook",
    "summarize_shadow_incident_snapshot",
    "validate_outlook_email_environment",
    "validate_test_delivery_policy",
    "run_observation_cycle",
]
